// Code generated by some-program. DO NOT EDIT.

package foo

func oneUnusedGenerated(a, b FooType) FooType {
	a += 1
	return a
}

func GeneratedCalls() {
	receivesSameFromGenerated(FooType(2))
	receivesSameFromGenerated(FooType(2))
	receivesSameFromGenerated(FooType(2))
	receivesSameFromGenerated(FooType(2))
}
